apiVersion: v2
name: argo
version: 0.1.0
dependencies:
- name: argo-workflows
  version: 0.22.1
  repository: https://argoproj.github.io/argo-helm
- name: argo-events
  version: 2.0.9
  repository: https://argoproj.github.io/argo-helm